### ISSUE TITLE
demo下MacOS Firefox无法通过验证

### ISSUE THREAD

**Issue by zerofancy** [wcaptcha/wcaptcha-js#4]
OS            macOS 14.3.1 23D60 arm64

名称 	Firefox
版本 	123.0
版本 ID 	20240213221259

控制台有如下输出：

Use default language zh [index.7c225165.js:171:170](https://wcaptcha.pingflash.com/assets/index.7c225165.js)
Binding events for form 
<form class="el-form el-form--default…abel-right demo-dynamic" style="max-width: 360px;" action="{document.location.href}">
[index.7c225165.js:171:170](https://wcaptcha.pingflash.com/assets/index.7c225165.js)
NetworkError: WorkerGlobalScope.importScripts: Failed to load worker script at blob:https://wcaptcha.pingflash.com/8e442972-d79b-4c69-92bc-d2b50dd15eb8 (nsresult = 0x80530013) [e5023a91-db9d-40f2-b983-68c2bf7a4221:1](blob:https://wcaptcha.pingflash.com/e5023a91-db9d-40f2-b983-68c2bf7a4221)
某些 Cookie 滥用推荐的“SameSite“属性 4

**Comment by zerofancy** [comment]
同一台设备下的Chrome可通过验证。

**Comment by greensea** [comment]
我手头上没有 Mac 设备，没法重现这个问题。
根据你的控制台输出，我看了一下代码，目前只能猜测可能是在 blob 中再次 importScript() 一个 blob 资源导致的，现在我修改了一下这部分代码，发布了一个新版本，你可以看看这个问题有没有解决

**Comment by zerofancy** [comment]
现在演示Demo表现是正确的。
